version: '3'
services:
  nginx:
   container_name: nginx
   image: nginx:1.15.3
   restart: always
   ports:
   - 80:80
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  
  app:
    restart: always
    build: ./app
    volumes:
      - ./app:/app
    expose:
      - "8080"
    depends_on:
      - nginx