version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.15.3
   restart: always
   ports:
   - 80:80
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:8.0.12
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - ./app:/app
    expose:
      - "8080"
    depends_on:
      - nginx
      - mysql